apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-2-loadgen
  labels:
    app: workload-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-2
  template:
    metadata:
      labels:
        app: workload-2
    spec:
      containers:
      - name: loadgen
        # IMPORTANT: Replace this with the path to your own image
        # e.g., gcr.io/your-project-id/load-generator:v4.0.0
        image: "us-central1-docker.pkg.dev/artemiollin-demo/gke-lab-repo/load-generator:v4.0.0"
        env:
        - name: TARGET_URL
          value: "http://workload-1-svc:8080/calculate"
        - name: DEFAULT_QPS
          value: "25"
        - name: DEFAULT_CONCURRENCY
          value: "10"
        - name: DEFAULT_CYCLE_LENGTH
          value: "60s"
        - name: SCALE_FACTOR
          value: "2"
        - name: NUMBER_OF_CYCLES
          value: "3"
        - name: WAIT_PERIOD
          value: "5s"
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
